---

- name: Creating Sonarqube volume
  docker_volume:
    name: "allspark_{{ item }}"
  with_items:
    - sonarqube_data
  when: allspark_sonarqube.enabled

- name: Starting Sonarqube master
  docker_container:
    name: sonarqube
    image: "{{ downloads.sonarqube.image }}:{{ downloads.sonarqube.tag }}"
    state: "{{ allspark_sonarqube.enabled and 'started' or 'absent'}}"
    purge_networks: true
    dns_servers: "{{allspark_dns_server}}"
    networks:
      - name: allspark
    volumes:
      - allspark_sonarqube_data:/opt/sonarqube/data
    labels:
      "heritage": "allspark"
    restart_policy: always
