haproxy_log_requests: true

haproxy_http_port: 80
haproxy_https_port: 443
gitlab_ssh_port: 2223

haproxy_endpoints:
    # Runtime name of the container
    # (defined by the `docker_container` module `name` parameter)
<<<<<<< HEAD
    name: "keycloak"
    # The host on which the service will be exposed
    host: "users.{{ allspark_root_domain }}"
    # An alias on the enabled feature toggle
    enabled: "{{ allspark_ldap.mode.federated_iam.enabled }}"
=======

    # The host on which the service will be exposed

    # An alias on the enabled feature toggle

>>>>>>> master
    # List of object with the following properties:
    # - mode: http|tcp
    # - port: the listening container port to expose
    # - exposed_port: The port exposed on the host machine (only for tcp mode)

      # # Sample HTTP backend
      # - port: 8080
      #   mode: http
      # # Sample TCP backend
      # - port: 6578
      #   mode: tcp
      #   exposed_port: 6578
<<<<<<< HEAD
      - mode: http
        port: 8080
=======

>>>>>>> master

  - name: prometheus
    host: "metrics.{{ allspark_root_domain }}"
    enabled: "{{ allspark_monitoring.enabled }}"
    backends:
    - mode: http
      port: 9090

  - name: grafana
    host: "monitoring.{{ allspark_root_domain }}"
    enabled: "{{ allspark_monitoring.enabled }}"
    backends:
    - mode: http
      port: 3000

  - name: gitlab
    host: "gitlab.{{ allspark_root_domain }}"
    enabled: "{{ allspark_gitlab.enabled }}"
    backends:
      # Port 22 here is because of a bug in the gitlab container :
      # even thus the gitlab_shell_ssh_port variable was set to 2223,
      # the git server is still launched on port 22.
    - port: 22
      mode: tcp
      exposed_port: "{{ gitlab_ssh_port }}"
    - port: 80
      mode: http

  - name: jenkins
    host: "jenkins.{{ allspark_root_domain }}"
    enabled: "{{ allspark_jenkins.enabled }}"
    backends:
    - mode: http
      port: 8080

<<<<<<< HEAD
=======
  - name: sonarqube
    host: "sonarqube.{{ allspark_root_domain }}"
    enabled: "{{ allspark_sonarqube.enabled }}"
    backends:
    - mode: http
      port: 9000

>>>>>>> master
  - name: mattermost
    enabled: "{{ allspark_mattermost.enabled }}"
    host: "mattermost.{{ allspark_root_domain }}"
    backends:
    - mode: http
      port: 80
