---
# defaults file for allspark

allspark_root_domain: allspark.localhost
allspark_root_directory: /opt/allspark
allspark_backup_directory: /opt/allspark/backup
allspark_admin_user: admin

# https://docs.gitlab.com/omnibus/settings/smtp.html
allspark_smtp:
  enabled: true
  host: mailtrap.io
  port: 2525
  username: username
  password: password
  tls: true
  domain: example.com

# Email Settings
allspark_email:
  enabled: true
  from: gitlab@example.com
  display: Gitlab
  reply: noreply@example.com


allspark_docker_version: "18.06"

allspark_dns_server: "8.8.8.8"

allspark_monitoring:
  enabled: false

allspark_haproxy:
  ssl:
    enabled: false
    # If SSL is enabled, you can set the directory from which
    # endpoints certificates will be imported with this variable.
    # Files in the local directory should be PEM formatted certificates
    # named like their endpoint (e.g: `infra.allspark.localhost.pem`)
    certificates_directory:
    # If selfsigned certificates are enabled, any certificate missing
    # for an endpoint will be created on the fly.
    # If selfsigned is disabled and a certificate is missing, the
    # install won't be able to complete successfully.
    selfsigned:
      enabled: false
      # For example country: FR
      country: XX
      state: state
      location: city
      organisation: myteam
      organizational_unit: myorganizational_unit

allspark_gitlab:
  enabled: true
  with_runner: false
  lfs_enabled: false

allspark_jenkins:
  enabled: false
  # Toggle default plugin import from release.
  import_plugins: false

allspark_sonarqube:
  enabled: false

allspark_mattermost:
  enabled: false

allspark_docker_registry:
  enabled: false

### Release configuration
# Should not be here
allspark_release_tmp_directory: /opt/allspark/release
allspark_release_destination: /opt/allspark.tar.gz
