# Images
gitlab_image: gitlab/gitlab-ce
keycloak_image: jboss/keycloak
haproxy_image: haproxy
haproxy_exporter_image: quay.io/prometheus/haproxy-exporter
grafana_image: grafana/grafana
prometheus_image: prom/prometheus
node_exporter_image: prom/node-exporter
sonarqube_image: sonarqube
gitlab_runner_image: gitlab/gitlab-runner
jenkins_image: actiniumio/jenkins
jenkins_slave_image: actiniumio/jnlp-slave
centos_image: centos
volumerize_image: blacklabelops/volumerize
mattermost_image: mattermost/mattermost-prod-app
postgresql_image: postgres
prometheus_alertmanager_image: prom/alertmanager
registry_image: library/registry

# Tags
gitlab_tag: latest
# Alpine tag is required, because it bundle rsyslogd
# which allow us to read logs from HAProxy
keycloak_tag: latest
haproxy_tag: alpine
haproxy_exporter_tag: v0.9.0
grafana_tag: latest
prometheus_tag: v2.1.0
node_exporter_tag: latest
sonarqube_tag: latest
gitlab_runner_tag: latest
jenkins_tag: latest
jenkins_slave_tag: latest
centos_tag: 7
volumerize_tag: latest
mattermost_tag: latest
postgresql_tag: latest
prometheus_alertmanager_tag: latest
registry_tag: latest

# Downloads
downloads:
  centos:
    enabled: true
    image: "{{ centos_image }}"
    tag: "{{ centos_tag }}"
  gitlab:
    enabled: "{{ allspark_gitlab.enabled }}"
    image: "{{ gitlab_image }}"
    tag: "{{ gitlab_tag }}"
  gitlab_runner:
    enabled: "{{ allspark_gitlab.with_runner }}"
    image: "{{ gitlab_runner_image }}"
    tag: "{{ gitlab_runner_tag }}"
  keycloak:
    enabled: "{{ allspark_ldap.enabled }}"
    image: "{{ keycloak_image }}"
    tag: "{{ keycloak_tag }}"
  grafana:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ grafana_image }}"
    tag: "{{ grafana_tag }}"
  jenkins:
    enabled: "{{ allspark_jenkins.enabled }}"
    image: "{{ jenkins_image }}"
    tag: "{{ jenkins_tag }}"
  jenkins_slave:
    enabled: "{{ allspark_jenkins.enabled }}"
    image: "{{ jenkins_slave_image }}"
    tag: "{{ jenkins_slave_tag }}"
  node_exporter:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ node_exporter_image }}"
    tag: "{{ node_exporter_tag }}"
  prometheus:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ prometheus_image }}"
    tag: "{{ prometheus_tag }}"
  sonarqube:
    enabled: "{{ allspark_sonarqube.enabled }}"
    image: "{{ sonarqube_image }}"
    tag: "{{ sonarqube_tag }}"
  haproxy:
    enabled: true
    image: "{{ haproxy_image }}"
    tag: "{{ haproxy_tag }}"
  haproxy_exporter:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ haproxy_exporter_image }}"
    tag: "{{ haproxy_exporter_tag }}"
  volumerize:
    enabled: true
    image: "{{ volumerize_image }}"
    tag: "{{ volumerize_tag }}"
  mattermost:
    enabled: "{{ allspark_mattermost.enabled }}"
    image: "{{ mattermost_image }}"
    tag: "{{ mattermost_tag }}"
  postgresql:
    enabled: "{{ allspark_mattermost.enabled or allspark_ldap.enabled }}"
    image: "{{ postgresql_image }}"
    tag: "{{ postgresql_tag }}"
  prometheus_alertmanager:
    enabled: "{{ allspark_monitoring.enabled }}"
    image: "{{ prometheus_alertmanager_image }}"
    tag: "{{ prometheus_alertmanager_tag }}"
  registry:
    enabled: "{{ allspark_docker_registry.enabled }}"
    image: "{{ registry_image }}"
    tag: "{{ registry_tag }}"

# Misc

## Set this to true to force the download of every images, even if they are
## disabled in the configuration
force_download: false
