- name: Allspark installer
  hosts: all
  roles:
    - system
    - local_datas
    - pip
    - { role: download, tags: [ "download", "prepare" ] }
    - network
    - haproxy
    - registry
    - utils
    #- monitoring
    - gitlab
    #- jenkins
    #- sonarqube
