- name: Gitlab mattermost data directory
  file:
    state: directory
    path: "{{ allspark_root_directory }}/data/mattermost"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0740
  become: yes

- name: Test Gitlab_Mattermost root password hash
  stat: path="{{ allspark_root_directory }}/data/mattermost/root_password_hash.txt"
  register: gitlab_root_password_file
  when: allspark_mattermost.enabled
  changed_when: false

- name: Test root password hash
  stat:
    path: "{{ allspark_root_directory }}/data/secrets/admin_password.txt"
    checksum_algorithm: sha256
  register: root_password_sha256
  when: allspark_mattermost.enabled
  changed_when: false

- name: Load mattermost root password hash
  command: "cat {{ allspark_root_directory }}/data/mattermost/root_password_hash.txt"
  changed_when: false
  when: allspark_mattermost.enabled and gitlab_root_password_file.stat.exists
  register: gitlab_root_password_hash

- name: Gitlab Mattermost root password hash
  shell: "echo {{ root_password_sha256.stat.checksum }} > {{ allspark_root_directory }}/data/mattermost/root_password_hash.txt"
  when: allspark_mattermost.enabled and (not gitlab_root_password_file.stat.exists or root_password_sha256.stat.checksum != gitlab_root_password_hash.stdout)
  changed_when: true
  notify:
    - restart_gitlab_mattermost
    - change_gitlab_mattermost_root_password

- name: Gitlab Mattermost config directory
  file:
    state: directory
    path: "{{ allspark_root_directory }}/config/mattermost"
  when: allspark_mattermost.enabled

- name: Gitlab Mattermost config File (gitlab_mattermost.rb.j2)
  template:
    src: templates/gitlab_mattermost.rb.j2
    dest: "{{ allspark_root_directory }}/config/mattermost/gitlab.rb"
  when: allspark_mattermost.enabled
  notify:
    - reconfigure_gitlab_mattermost

- name: Gitlab Mattermost volumes
  docker_volume:
    name: "allspark_{{ item }}"
  with_items:
    - mattermost_data
    - mattermost_config
  when: allspark_mattermost.enabled


- name: Gitlab image within mattermost deployed
  docker_container:
    name: mattermost
    state: "{{ allspark_gitlab.enabled and 'started' or 'absent'}}"
    image: "{{ downloads.gitlab.image }}:{{ downloads.gitlab.tag }}"
    hostname: "mattermost.{{ allspark_root_domain }}"
    volumes:
      - "allspark_mattermost_data:/var/opt/gitlab"
      - "allspark_mattermost_config:/etc/gitlab"
      - "{{ allspark_root_directory }}/config/mattermost/gitlab.rb:/etc/gitlab/gitlab.rb"
      - "{{ allspark_root_directory }}/data/secrets/admin_password.txt:/run/secrets/admin_password.txt"
    restart_policy: always
    purge_networks: true
    networks:
      - name: allspark
    labels:
      "heritage": "allspark"
  notify:
    - reconfigure_gitlab_mattermost
#    - migrate_gitlab_mattermost